apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: booking
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: booking
        image: sgse2021containerregistry.azurecr.io/booking:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: booking
spec:
  ports:
  - port: 8080
  selector:
    app: booking
