apiVersion: apps/v1
kind: Deployment
metadata:
  name: stundenplan-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stundenplan-frontend
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: stundenplan-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: stundenplan-frontend
        image: sgse2021cr.azurecr.io/ms_stundenplan-frontend:latest
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: stundenplan-frontend
spec:
  ports:
  - port: 8080
  selector:
    app: stundenplan-frontend
