apiVersion: apps/v1
kind: Deployment
metadata:
  name: stundenplan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stundenplan
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: stundenplan
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: stundenplan
        image: sgse2021containerregistry.azurecr.io/ms_stundenplan:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stundenplan
spec:
  ports:
  - port: 8080
  selector:
    app: stundenplan
