apiVersion: apps/v1
kind: Deployment
metadata:
  name: stundenplan-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stundenplan-backend
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 1
  #     maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: stundenplan-backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: stundenplan-backend
        image: sgse2021cr.azurecr.io/ms_stundenplan-backend:latest
        env: 
        - name: DATABASE_URL
          valueFrom: 
            secretKeyRef: 
              name: bookingsdb-secret
              key: url
        - name: DATABASE_USER
          valueFrom: 
            secretKeyRef: 
              name: bookingsdb-secret
              key: user
        - name: DATABASE_PASSWORD
          valueFrom: 
            secretKeyRef: 
              name: bookingsdb-secret
              key: password
        - name: DATABASE_NAME
          valueFrom: 
            secretKeyRef: 
              name: bookingsdb-secret
              key: database   

        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: stundenplan-backend
spec:
  ports:
  - port: 8080
  selector:
    app: stundenplan-backend
